---
# tasks file for bastion
- name: Get IPs using getent
  ansible.builtin.command: "getent hosts {{ item }}"
  register: getent_output
  loop: "{{ host_list }}"
  changed_when: false

- name: Add entries to /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item.stdout.split()[0] }} {{ item.item }}"
    state: present
  loop: "{{ getent_output.results }}"
